[versions]
coreKtx = "1.12.0"
hiltAndroid = "2.48"
lifecycleViewmodelCompose = "2.7.0"
runtimeLivedataCompose = "1.6.4"
room_version = "2.6.1"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
runtime-livedata-compose = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedataCompose" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room_version" }
room-common = { module = "androidx.room:room-common", version.ref = "room_version" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room_version" }

[plugins]

